-- Migration number: 0003 	2026-08-10T11:21:59.446Z

-- Generated by scripts/generate-seed-sql.mjs from the six hand-written
-- MDX files that were the source of truth before this migration.

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('adipiscing-elit-sed', 'Adipiscing Elit Sed', 'COLD BLUE', 'essay', 6, '2025.11', 'ESSAY', 'ESSAY', 'Duis aute irure dolor in reprehenderit in voluptate velit esse.', NULL, NULL, 'rgba(255,0,168,.05)', 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur, sed do eiusmod tempor incididunt ut labore.

Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil
molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas.

> Itaque earum rerum hic tenetur a sapiente delectus.

Ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis
doloribus asperiores repellat, omnis dolor repellendus.');

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('lorem-ipsum-dolor', 'Lorem Ipsum Dolor', 'BRUSHED STEEL', 'essay', 4, '2026.04', 'ESSAY', 'ESSAY', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod.', NULL, NULL, 'rgba(0,229,255,.05)', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

> Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.

Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed
quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.');

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('my-9-favourite-albums', 'My 9 Favourite Albums', 'NEON CHROME', 'list', 2, '2026.05', 'RANKED LIST · SOUND', '09', 'The records that scored the years. Ranked, defensible, non-negotiable.', 'RANKED · SOUND', 'linear-gradient(165deg, #101a1c, #07080a 62%)', NULL, NULL);
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 1, 'TITLE_01', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 2, 'TITLE_02', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 3, 'TITLE_03', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 4, 'TITLE_04', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 5, 'TITLE_05', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 6, 'TITLE_06', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 7, 'TITLE_07', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 8, 'TITLE_08', 'YEAR · LABEL');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-albums'), 9, 'TITLE_09', 'YEAR · LABEL');

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('my-9-favourite-manga', 'My 9 Favourite Manga', 'ACID INK', 'list', 3, '2026.05', 'RANKED LIST · INK', '09', 'Ink, panels, and the long arcs worth the years.', 'RANKED · INK', 'linear-gradient(165deg, #161a10, #07080a 62%)', NULL, NULL);
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 1, 'TITLE_01', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 2, 'TITLE_02', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 3, 'TITLE_03', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 4, 'TITLE_04', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 5, 'TITLE_05', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 6, 'TITLE_06', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 7, 'TITLE_07', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 8, 'TITLE_08', 'YEAR · AUTHOR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-manga'), 9, 'TITLE_09', 'YEAR · AUTHOR');

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('my-9-favourite-movies', 'My 9 Favourite Movies', 'STATIC RED', 'list', 1, '2026.05', 'RANKED LIST · CINEMA', '09', 'Nine films, ranked. Once for the story, once for the seams.', 'RANKED · CINEMA', 'linear-gradient(165deg, #1a1013, #07080a 62%)', NULL, NULL);
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 1, 'The Truman Show', '1998 · PETER WEIR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 2, 'Pulp Fiction', '1994 · QUENTIN TARANTINO');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 3, 'Fight Club', '1999 · DAVID FINCHER');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 4, 'City of God', '2002 · F. MEIRELLES & K. LUND');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 5, '12 Angry Men', '1957 · SIDNEY LUMET');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 6, 'Ferris Bueller''s Day Off', '1986 · JOHN HUGHES');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 7, 'Sin City', '2005 · R. RODRIGUEZ & F. MILLER');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 8, 'Dead Poets Society', '1989 · PETER WEIR');
INSERT INTO article_items (article_id, position, title, meta) VALUES ((SELECT id FROM articles WHERE slug = 'my-9-favourite-movies'), 9, 'Seven Samurai', '1954 · AKIRA KUROSAWA');

INSERT INTO articles (slug, title, skin, type, sort_order, date, kicker, badge, excerpt, blog_kicker, blog_background, blog_tint, body) VALUES ('sit-amet-consectetur', 'Sit Amet Consectetur', 'MAGENTA BURN', 'essay', 5, '2026.02', 'ESSAY', 'ESSAY', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.', NULL, NULL, 'rgba(163,255,18,.05)', 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur
adipiscing elit.

At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis
praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias.

> Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus.

Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore,
cum soluta nobis est eligendi optio cumque nihil impedit quo minus.');
